// Content Script: Inject article generation button + modal on YouTube pages
// Adapted from tube2trans/src/content/ytcontent.js

(function() {
  'use strict';

  // Prevent double loading
  if (window._ytArticleGenLoaded) return;
  window._ytArticleGenLoaded = true;

  console.log('[YT-Article] ===== Content script starting =====');
  console.log('[YT-Article] URL:', location.href);

  // ================================================================
  // Transcript extraction (from tube2trans)
  // ================================================================
  function unescapeUrl(url) {
    if (!url) return '';
    return url.replace(/\\u0026/g, '&').replace(/\\\//g, '/').replace(/&amp;/g, '&');
  }

  function extractCaptionTracks() {
    const pageHtml = document.documentElement.innerHTML;

    // Method 1: bracket counting
    const captionStart = pageHtml.indexOf('"captionTracks":[');
    if (captionStart !== -1) {
      try {
        const arrayStart = captionStart + '"captionTracks":'.length;
        let depth = 0, arrayEnd = -1;
        for (let i = arrayStart; i < pageHtml.length && i < arrayStart + 50000; i++) {
          if (pageHtml[i] === '[') depth++;
          else if (pageHtml[i] === ']') { depth--; if (depth === 0) { arrayEnd = i + 1; break; } }
        }
        if (arrayEnd !== -1) {
          let jsonStr = pageHtml.substring(arrayStart, arrayEnd)
            .replace(/\\u0026/g, '&').replace(/\\\//g, '/');
          const tracks = JSON.parse(jsonStr);
          if (tracks && tracks.length > 0) {
            return tracks.map(t => ({
              languageCode: t.languageCode,
              name: t.name?.simpleText || t.languageCode,
              baseUrl: unescapeUrl(t.baseUrl),
              isAutoGenerated: t.kind === 'asr',
            }));
          }
        }
      } catch (e) { console.log('[YT-Article] Method 1 parse failed:', e.message); }
    }

    // Method 2: timedtext regex
    const regex = /"baseUrl"\s*:\s*"(https?:[^"]*timedtext[^"]*)"/g;
    const matches = [];
    let m;
    while ((m = regex.exec(pageHtml)) !== null) matches.push(m[1]);
    if (matches.length > 0) {
      return matches.map((rawUrl, i) => {
        const url = unescapeUrl(rawUrl);
        const langMatch = url.match(/lang=([a-z]{2,3})/);
        return {
          languageCode: langMatch ? langMatch[1] : `lang${i}`,
          name: langMatch ? langMatch[1].toUpperCase() : `Track ${i + 1}`,
          baseUrl: url,
          isAutoGenerated: url.includes('kind=asr'),
        };
      });
    }
    return [];
  }

  async function fetchTranscript(baseUrl) {
    const r = await fetch(baseUrl);
    const text = await r.text();
    if (!text || !text.trim()) return [];

    if (text.trim().startsWith('<')) {
      // XML format
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'text/xml');
      const nodes = doc.querySelectorAll('text');
      return Array.from(nodes).filter(n => n.textContent.trim()).map(n => ({
        start: parseFloat(n.getAttribute('start')),
        duration: parseFloat(n.getAttribute('dur') || '0'),
        text: n.textContent.trim(),
      }));
    } else {
      // JSON format
      const data = JSON.parse(text);
      if (!data.events) return [];
      return data.events.filter(e => e.segs).map(e => ({
        start: (e.tStartMs || 0) / 1000,
        duration: (e.dDurationMs || 0) / 1000,
        text: e.segs.map(s => s.utf8).join('').trim(),
      })).filter(e => e.text);
    }
  }

  async function getTranscript(langHint) {
    const tracks = extractCaptionTracks();
    if (tracks.length === 0) return { entries: [], lang: 'none', error: 'No captions found' };

    let track;
    if (langHint) {
      track = tracks.find(t => t.languageCode === langHint) || tracks[0];
    } else {
      track = tracks.find(t => t.languageCode === 'ja')
           || tracks.find(t => t.languageCode === 'en')
           || tracks[0];
    }

    try {
      const entries = await fetchTranscript(track.baseUrl);
      return { entries, lang: track.languageCode, error: null };
    } catch (e) {
      return { entries: [], lang: track.languageCode, error: e.message };
    }
  }

  function getVideoTitle() {
    const el = document.querySelector('h1.ytd-watch-metadata yt-formatted-string')
            || document.querySelector('h1 yt-formatted-string');
    if (el) return el.textContent.trim();
    const title = document.title;
    return title.endsWith(' - YouTube') ? title.slice(0, -10) : title;
  }

  // ================================================================
  // Button styles (inline - no external CSS dependency)
  // ================================================================
  const BTN_STYLE = [
    'background: #065fd4',
    'color: #fff',
    'border: none',
    'padding: 8px 16px',
    'border-radius: 18px',
    'cursor: pointer',
    'font-size: 14px',
    'font-weight: 500',
    'font-family: "YouTube Sans", "Roboto", sans-serif',
    'display: inline-flex',
    'align-items: center',
    'gap: 6px',
    'margin-left: 8px',
    'white-space: nowrap',
    'height: 36px',
    'box-sizing: border-box',
    'vertical-align: middle',
    'flex-shrink: 0',
    'z-index: 9999',
    'position: relative',
    'opacity: 1',
    'visibility: visible',
    'line-height: 36px',
    'letter-spacing: 0.5px',
  ].join(' !important; ') + ' !important;';

  const FLOAT_BTN_STYLE = [
    'position: fixed',
    'bottom: 80px',
    'right: 20px',
    'background: #065fd4',
    'color: #fff',
    'border: none',
    'padding: 12px 20px',
    'border-radius: 24px',
    'cursor: pointer',
    'font-size: 15px',
    'font-weight: 600',
    'font-family: "YouTube Sans", "Roboto", sans-serif',
    'z-index: 99999',
    'box-shadow: 0 4px 12px rgba(0,0,0,0.3)',
    'opacity: 1',
    'visibility: visible',
    'display: flex',
    'align-items: center',
    'gap: 8px',
  ].join(' !important; ') + ' !important;';

  // ================================================================
  // Button injection
  // ================================================================
  let currentVideoId = null;

  function extractVideoId(url) {
    const m = url.match(/[?&]v=([A-Za-z0-9_-]{11})/);
    return m ? m[1] : null;
  }

  function createButton(style) {
    const btn = document.createElement('button');
    btn.className = 'yt-article-gen-btn';
    btn.id = 'yt-article-gen-btn';
    btn.textContent = '\u{1F4DD} \u8A18\u4E8B\u5316'; // 📝 記事化
    btn.setAttribute('style', style);
    btn.addEventListener('click', showModal);
    btn.addEventListener('mouseenter', function() {
      this.style.background = '#0356c4';
    });
    btn.addEventListener('mouseleave', function() {
      this.style.background = '#065fd4';
    });
    return btn;
  }

  let injectRetries = 0;
  const MAX_INJECT_RETRIES = 30;

  function injectButton() {
    // Already exists?
    if (document.getElementById('yt-article-gen-btn')) {
      console.log('[YT-Article] Button already exists');
      return;
    }

    console.log('[YT-Article] Attempting button injection, retry:', injectRetries);

    // Try multiple selectors in order
    const selectors = [
      '#top-row',                                    // top row with owner+actions
      '#above-the-fold #top-row',                    // more specific
      'ytd-watch-metadata #top-row',                 // even more specific
      '#actions #top-level-buttons-computed',         // inside buttons area
      '#actions',                                    // actions container
      '#above-the-fold',                             // above the fold area
      '#below',                                      // below player area
      'ytd-watch-flexy #columns #primary #primary-inner', // primary content
    ];

    for (const selector of selectors) {
      const container = document.querySelector(selector);
      if (container) {
        console.log('[YT-Article] Found container:', selector);
        const btn = createButton(BTN_STYLE);
        container.appendChild(btn);

        // Verify
        if (document.getElementById('yt-article-gen-btn')) {
          console.log('[YT-Article] Button injected successfully in:', selector);
          injectRetries = 0;
          return;
        } else {
          console.log('[YT-Article] Button was rejected by:', selector);
        }
      }
    }

    // Fallback: floating button fixed to viewport
    console.log('[YT-Article] All selectors failed, using floating button');
    const floatBtn = createButton(FLOAT_BTN_STYLE);
    document.body.appendChild(floatBtn);

    if (document.getElementById('yt-article-gen-btn')) {
      console.log('[YT-Article] Floating button injected successfully');
      injectRetries = 0;
      return;
    }

    // If even body append failed, retry
    injectRetries++;
    if (injectRetries < MAX_INJECT_RETRIES) {
      console.log('[YT-Article] All injection methods failed, retrying in 1s...');
      setTimeout(injectButton, 1000);
    } else {
      console.error('[YT-Article] FAILED to inject button after', MAX_INJECT_RETRIES, 'retries');
    }
  }

  function removeButton() {
    const btn = document.getElementById('yt-article-gen-btn');
    if (btn) btn.remove();
  }

  function checkForVideo() {
    const vid = extractVideoId(location.href);
    console.log('[YT-Article] checkForVideo:', vid, 'current:', currentVideoId);

    if (vid && vid !== currentVideoId) {
      currentVideoId = vid;
      removeButton();
      removeModal();
      injectRetries = 0;
      console.log('[YT-Article] New video detected:', vid);
      setTimeout(injectButton, 2000); // Wait for YouTube SPA render
    } else if (vid && vid === currentVideoId && !document.getElementById('yt-article-gen-btn')) {
      // Video same but button gone (YouTube re-rendered), re-inject
      injectRetries = 0;
      console.log('[YT-Article] Button missing, re-injecting for:', vid);
      setTimeout(injectButton, 500);
    } else if (!vid) {
      currentVideoId = null;
      removeButton();
      removeModal();
    }
  }

  // ================================================================
  // Modal
  // ================================================================
  function showModal() {
    if (document.querySelector('.yt-article-modal-overlay')) return;

    const overlay = document.createElement('div');
    overlay.className = 'yt-article-modal-overlay';
    overlay.innerHTML = `
      <div class="yt-article-modal">
        <h2>YouTube Article Generator</h2>
        <div id="yt-article-form">
          <label>\u6295\u7A3F\u5148\u30D7\u30E9\u30C3\u30C8\u30D5\u30A9\u30FC\u30E0</label>
          <select id="yt-art-platform">
            <option value="life">LIFE (\u500B\u4EBA\u30CA\u30EC\u30C3\u30B8)</option>
            <option value="zenn">Zenn (\u6280\u8853\u8A18\u4E8B)</option>
            <option value="qiita">Qiita (\u6280\u8853\u8A18\u4E8B)</option>
            <option value="note">note (\u30A8\u30C3\u30BB\u30A4\u30FB\u6599\u7406)</option>
            <option value="cookpad">Cookpad (\u6599\u7406\u5C02\u7528)</option>
          </select>

          <label>\u30B9\u30BF\u30A4\u30EB</label>
          <select id="yt-art-style">
            <option value="auto">\u81EA\u52D5\u5224\u5B9A</option>
            <option value="\u6280\u8853\u89E3\u8AAC\u8A18\u4E8B\uFF08Qiita/Zenn\u98A8\uFF09">\u6280\u8853\u89E3\u8AAC\u8A18\u4E8B</option>
            <option value="\u5165\u9580\u30C1\u30E5\u30FC\u30C8\u30EA\u30A2\u30EB">\u5165\u9580\u30C1\u30E5\u30FC\u30C8\u30EA\u30A2\u30EB</option>
            <option value="\u6DF1\u5800\u308A\u89E3\u8AAC\uFF08\u66F8\u7C4D\u7AE0\u98A8\uFF09">\u6DF1\u5800\u308A\u89E3\u8AAC</option>
            <option value="\u6BD4\u8F03\u30FB\u8003\u5BDF\u8A18\u4E8B">\u6BD4\u8F03\u30FB\u8003\u5BDF\u8A18\u4E8B</option>
            <option value="\u30CF\u30F3\u30BA\u30AA\u30F3\u8A18\u4E8B">\u30CF\u30F3\u30BA\u30AA\u30F3\u8A18\u4E8B</option>
            <option value="\u30EC\u30B7\u30D4\u8A18\u4E8B">\u30EC\u30B7\u30D4\u8A18\u4E8B</option>
          </select>

          <label>\u96E3\u6613\u5EA6</label>
          <select id="yt-art-difficulty">
            <option value="\u521D\u5FC3\u8005\u5411\u3051">\u521D\u5FC3\u8005\u5411\u3051</option>
            <option value="\u4E2D\u7D1A\u8005\u5411\u3051" selected>\u4E2D\u7D1A\u8005\u5411\u3051</option>
            <option value="\u4E0A\u7D1A\u8005\u5411\u3051">\u4E0A\u7D1A\u8005\u5411\u3051</option>
            <option value="\u5C02\u9580\u5BB6\u5411\u3051">\u5C02\u9580\u5BB6\u5411\u3051</option>
          </select>

          <label>\u5BFE\u8C61\u8AAD\u8005</label>
          <input type="text" id="yt-art-audience" value="\u30A8\u30F3\u30B8\u30CB\u30A2\u5168\u822C" />

          <label>\u8A18\u4E8B\u30BF\u30A4\u30C8\u30EB\uFF08\u7A7A\u6B04\u3067AI\u81EA\u52D5\u751F\u6210\uFF09</label>
          <input type="text" id="yt-art-title" placeholder="\u7701\u7565\u53EF" />

          <div class="yt-article-modal-actions">
            <button class="yt-article-btn-cancel" id="yt-art-cancel">\u30AD\u30E3\u30F3\u30BB\u30EB</button>
            <button class="yt-article-btn-generate" id="yt-art-generate">\u8A18\u4E8B\u3092\u751F\u6210</button>
          </div>
        </div>
        <div id="yt-article-progress" class="yt-article-progress" style="display:none;"></div>
        <div id="yt-article-result" style="display:none;"></div>
        <div id="yt-article-error" class="yt-article-error" style="display:none;"></div>
      </div>
    `;

    document.body.appendChild(overlay);

    // Load saved defaults
    try {
      chrome.storage.local.get(['defaults'], (data) => {
        const d = data.defaults || {};
        if (d.platform) document.getElementById('yt-art-platform').value = d.platform;
        if (d.difficulty) document.getElementById('yt-art-difficulty').value = d.difficulty;
        if (d.audience) document.getElementById('yt-art-audience').value = d.audience;
        if (d.style) document.getElementById('yt-art-style').value = d.style;
      });
    } catch (e) {
      console.log('[YT-Article] Could not load defaults:', e.message);
    }

    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) removeModal();
    });
    document.getElementById('yt-art-cancel').addEventListener('click', removeModal);
    document.getElementById('yt-art-generate').addEventListener('click', startGeneration);
  }

  function removeModal() {
    const overlay = document.querySelector('.yt-article-modal-overlay');
    if (overlay) overlay.remove();
  }

  function updateProgress(steps) {
    const el = document.getElementById('yt-article-progress');
    if (!el) return;
    el.style.display = 'block';
    el.innerHTML = steps.map(s =>
      `<div class="step ${s.status}">${s.label}</div>`
    ).join('');
  }

  async function startGeneration() {
    const btn = document.getElementById('yt-art-generate');
    btn.disabled = true;
    btn.textContent = '\u751F\u6210\u4E2D...';
    document.getElementById('yt-article-error').style.display = 'none';
    document.getElementById('yt-article-result').style.display = 'none';

    const steps = [
      { label: '\u5B57\u5E55\u3092\u53D6\u5F97\u4E2D...', status: 'active' },
      { label: 'AI\u8A18\u4E8B\u3092\u751F\u6210\u4E2D...', status: '' },
      { label: 'GitHub\u306B\u4FDD\u5B58\u4E2D...', status: '' },
    ];
    updateProgress(steps);

    try {
      // Step 1: Get transcript
      const { entries, lang, error } = await getTranscript(null);
      if (error || entries.length === 0) {
        throw new Error(error || '\u5B57\u5E55\u304C\u53D6\u5F97\u3067\u304D\u307E\u305B\u3093\u3067\u3057\u305F');
      }

      steps[0].status = 'done';
      steps[1].status = 'active';
      updateProgress(steps);

      // Step 2 & 3: Send to service worker for AI generation + GitHub save
      const result = await chrome.runtime.sendMessage({
        type: 'GENERATE_ARTICLE',
        data: {
          videoId: currentVideoId,
          url: location.href.split('&t=')[0],
          transcript: entries,
          videoTitle: getVideoTitle(),
          platform: document.getElementById('yt-art-platform').value,
          style: document.getElementById('yt-art-style').value,
          difficulty: document.getElementById('yt-art-difficulty').value,
          audience: document.getElementById('yt-art-audience').value,
          titleOverride: document.getElementById('yt-art-title').value || null,
          lang,
        },
      });

      if (result.error) throw new Error(result.error);

      steps[1].status = 'done';
      steps[2].status = 'done';
      updateProgress(steps);

      // Show result
      const resultEl = document.getElementById('yt-article-result');
      resultEl.style.display = 'block';
      resultEl.innerHTML = `
        <div class="yt-article-result">
          <h3>\u8A18\u4E8B\u5316\u5B8C\u4E86</h3>
          <p><strong>${result.articleTitle}</strong></p>
          <p>\u30B8\u30E3\u30F3\u30EB: ${result.genre} | AI: ${result.provider} | ${result.articleChars.toLocaleString()}\u6587\u5B57</p>
          <p><a href="${result.githubUrl}" target="_blank">GitHub\u3067\u8A18\u4E8B\u3092\u898B\u308B</a></p>
          <div class="yt-article-result-actions">
            <button id="yt-art-copy">\u8A18\u4E8B\u3092\u30B3\u30D4\u30FC</button>
            <button id="yt-art-close">\u9589\u3058\u308B</button>
          </div>
        </div>
      `;

      document.getElementById('yt-art-copy').addEventListener('click', () => {
        navigator.clipboard.writeText(result.articleContent);
        document.getElementById('yt-art-copy').textContent = '\u30B3\u30D4\u30FC\u6E08\u307F!';
      });
      document.getElementById('yt-art-close').addEventListener('click', removeModal);

    } catch (e) {
      const errEl = document.getElementById('yt-article-error');
      errEl.style.display = 'block';
      errEl.textContent = `\u30A8\u30E9\u30FC: ${e.message}`;
      btn.disabled = false;
      btn.textContent = '\u8A18\u4E8B\u3092\u751F\u6210';
    }
  }

  // ================================================================
  // Message listener
  // ================================================================
  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg.type === 'UPDATE_PROGRESS') {
      console.log('[YT-Article] Progress:', msg.message);
    }
    return false;
  });

  // ================================================================
  // SPA navigation observer
  // ================================================================
  let lastUrl = location.href;
  const observer = new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      checkForVideo();
    }
  });
  observer.observe(document.body, { childList: true, subtree: true });

  // Initial check
  checkForVideo();

  // Periodic check: YouTube SPA may re-render and remove our button
  setInterval(() => {
    if (currentVideoId && !document.getElementById('yt-article-gen-btn')) {
      console.log('[YT-Article] Periodic check: button missing, re-injecting');
      injectRetries = 0;
      injectButton();
    }
  }, 3000);

  console.log('[YT-Article] Content script loaded successfully');
})();
