// Content Script: Inject article generation button + modal on YouTube pages
// Adapted from tube2trans/src/content/ytcontent.js

if (typeof window._ytArticleGenLoaded === 'undefined') {
  window._ytArticleGenLoaded = true;

  // ================================================================
  // Transcript extraction (from tube2trans)
  // ================================================================
  function unescapeUrl(url) {
    if (!url) return '';
    return url.replace(/\\u0026/g, '&').replace(/\\\//g, '/').replace(/&amp;/g, '&');
  }

  function extractCaptionTracks() {
    const pageHtml = document.documentElement.innerHTML;

    // Method 1: bracket counting
    const captionStart = pageHtml.indexOf('"captionTracks":[');
    if (captionStart !== -1) {
      try {
        const arrayStart = captionStart + '"captionTracks":'.length;
        let depth = 0, arrayEnd = -1;
        for (let i = arrayStart; i < pageHtml.length && i < arrayStart + 50000; i++) {
          if (pageHtml[i] === '[') depth++;
          else if (pageHtml[i] === ']') { depth--; if (depth === 0) { arrayEnd = i + 1; break; } }
        }
        if (arrayEnd !== -1) {
          let jsonStr = pageHtml.substring(arrayStart, arrayEnd)
            .replace(/\\u0026/g, '&').replace(/\\\//g, '/');
          const tracks = JSON.parse(jsonStr);
          if (tracks && tracks.length > 0) {
            return tracks.map(t => ({
              languageCode: t.languageCode,
              name: t.name?.simpleText || t.languageCode,
              baseUrl: unescapeUrl(t.baseUrl),
              isAutoGenerated: t.kind === 'asr',
            }));
          }
        }
      } catch (e) { console.log('[YT-Article] Method 1 parse failed:', e.message); }
    }

    // Method 2: timedtext regex
    const regex = /"baseUrl"\s*:\s*"(https?:[^"]*timedtext[^"]*)"/g;
    const matches = [];
    let m;
    while ((m = regex.exec(pageHtml)) !== null) matches.push(m[1]);
    if (matches.length > 0) {
      return matches.map((rawUrl, i) => {
        const url = unescapeUrl(rawUrl);
        const langMatch = url.match(/lang=([a-z]{2,3})/);
        return {
          languageCode: langMatch ? langMatch[1] : `lang${i}`,
          name: langMatch ? langMatch[1].toUpperCase() : `Track ${i + 1}`,
          baseUrl: url,
          isAutoGenerated: url.includes('kind=asr'),
        };
      });
    }
    return [];
  }

  async function fetchTranscript(baseUrl) {
    const r = await fetch(baseUrl);
    const text = await r.text();
    if (!text || !text.trim()) return [];

    if (text.trim().startsWith('<')) {
      // XML format
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'text/xml');
      const nodes = doc.querySelectorAll('text');
      return Array.from(nodes).filter(n => n.textContent.trim()).map(n => ({
        start: parseFloat(n.getAttribute('start')),
        duration: parseFloat(n.getAttribute('dur') || '0'),
        text: n.textContent.trim(),
      }));
    } else {
      // JSON format
      const data = JSON.parse(text);
      if (!data.events) return [];
      return data.events.filter(e => e.segs).map(e => ({
        start: (e.tStartMs || 0) / 1000,
        duration: (e.dDurationMs || 0) / 1000,
        text: e.segs.map(s => s.utf8).join('').trim(),
      })).filter(e => e.text);
    }
  }

  async function getTranscript(langHint) {
    const tracks = extractCaptionTracks();
    if (tracks.length === 0) return { entries: [], lang: 'none', error: 'No captions found' };

    let track;
    if (langHint) {
      track = tracks.find(t => t.languageCode === langHint) || tracks[0];
    } else {
      track = tracks.find(t => t.languageCode === 'ja')
           || tracks.find(t => t.languageCode === 'en')
           || tracks[0];
    }

    try {
      const entries = await fetchTranscript(track.baseUrl);
      return { entries, lang: track.languageCode, error: null };
    } catch (e) {
      return { entries: [], lang: track.languageCode, error: e.message };
    }
  }

  function getVideoTitle() {
    const el = document.querySelector('h1.ytd-watch-metadata yt-formatted-string')
            || document.querySelector('h1 yt-formatted-string');
    if (el) return el.textContent.trim();
    const title = document.title;
    return title.endsWith(' - YouTube') ? title.slice(0, -10) : title;
  }

  // ================================================================
  // Button injection
  // ================================================================
  let currentVideoId = null;

  function extractVideoId(url) {
    const m = url.match(/[?&]v=([A-Za-z0-9_-]{11})/);
    return m ? m[1] : null;
  }

  function injectButton() {
    if (document.querySelector('.yt-article-gen-btn')) return;

    const actionsContainer =
      document.querySelector('#actions #top-level-buttons-computed') ||
      document.querySelector('#actions ytd-menu-renderer') ||
      document.querySelector('ytd-watch-metadata #actions');

    if (!actionsContainer) {
      setTimeout(injectButton, 1000);
      return;
    }

    const btn = document.createElement('button');
    btn.className = 'yt-article-gen-btn';
    btn.textContent = '記事化';
    btn.addEventListener('click', showModal);
    actionsContainer.appendChild(btn);
  }

  function removeButton() {
    const btn = document.querySelector('.yt-article-gen-btn');
    if (btn) btn.remove();
  }

  function checkForVideo() {
    const vid = extractVideoId(location.href);
    if (vid && vid !== currentVideoId) {
      currentVideoId = vid;
      removeButton();
      removeModal();
      setTimeout(injectButton, 1500); // Wait for YouTube SPA render
    } else if (!vid) {
      currentVideoId = null;
      removeButton();
      removeModal();
    }
  }

  // ================================================================
  // Modal
  // ================================================================
  function showModal() {
    if (document.querySelector('.yt-article-modal-overlay')) return;

    const overlay = document.createElement('div');
    overlay.className = 'yt-article-modal-overlay';
    overlay.innerHTML = `
      <div class="yt-article-modal">
        <h2>YouTube Article Generator</h2>
        <div id="yt-article-form">
          <label>投稿先プラットフォーム</label>
          <select id="yt-art-platform">
            <option value="life">LIFE (個人ナレッジ)</option>
            <option value="zenn">Zenn (技術記事)</option>
            <option value="qiita">Qiita (技術記事)</option>
            <option value="note">note (エッセイ・料理)</option>
            <option value="cookpad">Cookpad (料理専用)</option>
          </select>

          <label>スタイル</label>
          <select id="yt-art-style">
            <option value="auto">自動判定</option>
            <option value="技術解説記事（Qiita/Zenn風）">技術解説記事</option>
            <option value="入門チュートリアル">入門チュートリアル</option>
            <option value="深堀り解説（書籍章風）">深堀り解説</option>
            <option value="比較・考察記事">比較・考察記事</option>
            <option value="ハンズオン記事">ハンズオン記事</option>
            <option value="レシピ記事">レシピ記事</option>
          </select>

          <label>難易度</label>
          <select id="yt-art-difficulty">
            <option value="初心者向け">初心者向け</option>
            <option value="中級者向け" selected>中級者向け</option>
            <option value="上級者向け">上級者向け</option>
            <option value="専門家向け">専門家向け</option>
          </select>

          <label>対象読者</label>
          <input type="text" id="yt-art-audience" value="エンジニア全般" />

          <label>記事タイトル（空欄でAI自動生成）</label>
          <input type="text" id="yt-art-title" placeholder="省略可" />

          <div class="yt-article-modal-actions">
            <button class="yt-article-btn-cancel" id="yt-art-cancel">キャンセル</button>
            <button class="yt-article-btn-generate" id="yt-art-generate">記事を生成</button>
          </div>
        </div>
        <div id="yt-article-progress" class="yt-article-progress" style="display:none;"></div>
        <div id="yt-article-result" style="display:none;"></div>
        <div id="yt-article-error" class="yt-article-error" style="display:none;"></div>
      </div>
    `;

    document.body.appendChild(overlay);

    // Load saved defaults
    chrome.storage.local.get(['defaults'], (data) => {
      const d = data.defaults || {};
      if (d.platform) document.getElementById('yt-art-platform').value = d.platform;
      if (d.difficulty) document.getElementById('yt-art-difficulty').value = d.difficulty;
      if (d.audience) document.getElementById('yt-art-audience').value = d.audience;
      if (d.style) document.getElementById('yt-art-style').value = d.style;
    });

    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) removeModal();
    });
    document.getElementById('yt-art-cancel').addEventListener('click', removeModal);
    document.getElementById('yt-art-generate').addEventListener('click', startGeneration);
  }

  function removeModal() {
    const overlay = document.querySelector('.yt-article-modal-overlay');
    if (overlay) overlay.remove();
  }

  function updateProgress(steps) {
    const el = document.getElementById('yt-article-progress');
    if (!el) return;
    el.style.display = 'block';
    el.innerHTML = steps.map(s =>
      `<div class="step ${s.status}">${s.label}</div>`
    ).join('');
  }

  async function startGeneration() {
    const btn = document.getElementById('yt-art-generate');
    btn.disabled = true;
    btn.textContent = '生成中...';
    document.getElementById('yt-article-error').style.display = 'none';
    document.getElementById('yt-article-result').style.display = 'none';

    const steps = [
      { label: '字幕を取得中...', status: 'active' },
      { label: 'AI記事を生成中...', status: '' },
      { label: 'GitHubに保存中...', status: '' },
    ];
    updateProgress(steps);

    try {
      // Step 1: Get transcript
      const { entries, lang, error } = await getTranscript(null);
      if (error || entries.length === 0) {
        throw new Error(error || '字幕が取得できませんでした');
      }

      steps[0].status = 'done';
      steps[1].status = 'active';
      updateProgress(steps);

      // Step 2 & 3: Send to service worker for AI generation + GitHub save
      const result = await chrome.runtime.sendMessage({
        type: 'GENERATE_ARTICLE',
        data: {
          videoId: currentVideoId,
          url: location.href.split('&t=')[0],
          transcript: entries,
          videoTitle: getVideoTitle(),
          platform: document.getElementById('yt-art-platform').value,
          style: document.getElementById('yt-art-style').value,
          difficulty: document.getElementById('yt-art-difficulty').value,
          audience: document.getElementById('yt-art-audience').value,
          titleOverride: document.getElementById('yt-art-title').value || null,
          lang,
        },
      });

      if (result.error) throw new Error(result.error);

      steps[1].status = 'done';
      steps[2].status = 'done';
      updateProgress(steps);

      // Show result
      const resultEl = document.getElementById('yt-article-result');
      resultEl.style.display = 'block';
      resultEl.innerHTML = `
        <div class="yt-article-result">
          <h3>記事化完了</h3>
          <p><strong>${result.articleTitle}</strong></p>
          <p>ジャンル: ${result.genre} | AI: ${result.provider} | ${result.articleChars.toLocaleString()}文字</p>
          <p><a href="${result.githubUrl}" target="_blank">GitHubで記事を見る</a></p>
          <div class="yt-article-result-actions">
            <button id="yt-art-copy">記事をコピー</button>
            <button id="yt-art-close">閉じる</button>
          </div>
        </div>
      `;

      document.getElementById('yt-art-copy').addEventListener('click', () => {
        navigator.clipboard.writeText(result.articleContent);
        document.getElementById('yt-art-copy').textContent = 'コピー済み!';
      });
      document.getElementById('yt-art-close').addEventListener('click', removeModal);

    } catch (e) {
      const errEl = document.getElementById('yt-article-error');
      errEl.style.display = 'block';
      errEl.textContent = `エラー: ${e.message}`;
      btn.disabled = false;
      btn.textContent = '記事を生成';
    }
  }

  // ================================================================
  // Message listener
  // ================================================================
  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (msg.type === 'UPDATE_PROGRESS') {
      // Could be used for more granular progress from service worker
      console.log('[YT-Article] Progress:', msg.message);
    }
    return false;
  });

  // ================================================================
  // SPA navigation observer
  // ================================================================
  let lastUrl = location.href;
  const observer = new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      checkForVideo();
    }
  });
  observer.observe(document.body, { childList: true, subtree: true });

  // Initial check
  checkForVideo();

  console.log('[YT-Article] Content script loaded');
}
